export const ProjectData = [
    {src: "src/assets/Project/ProjectsImg/random-quote-machine.png", 
        alt: "Random quote machine", 
        descriptionES: (<>En este proyecto desarrollé una aplicación de frases aleatorias utilizando <span className="text-blue-500 text-xl">React</span> y <span className="text-blue-500 text-xl">jQuery</span>. Además utilicé <code>useEffect</code> para gestionar el cambio automático de frases y añadí cambio de color al fondo para añadir más dinamismo.</>) , 
        descriptionEN:(<>For this project, I built a random quote app with <span className="text-blue-500 text-xl">React</span> and <span className="text-blue-500 text-xl">jQuery</span>. I used <code>useEffect</code> to switch quotes automatically and added background color changes to make it feel more dynamic.</>), 
        type:"Front end", 
        githubLink: "https://github.com/Dev-id-A/random-quote-machine", 
        pagesLink:"https://dev-id-a.github.io/random-quote-machine/"
        ,},
    {src: "src/assets/Project/ProjectsImg/markdown-previewer.png", 
        alt: "Markdown previewer", 
        descriptionES: (<>En este proyecto desarrollé una aplicación de Markdown utilizando <span className="text-blue-500 text-xl">React</span>, <span className="text-blue-500 text-xl">Bootstrap</span> y una <span className="text-blue-500 text-xl">API de Markdown</span>. Con ella puedes escribir en un <code>textarea</code> y ver inmediatamente cómo se representa el contenido en el contenedor de al lado.</>), 
        descriptionEN: (<>In this project, I built a Markdown application using <span className="text-blue-500 text-xl">React</span>, <span className="text-blue-500 text-xl">Bootstrap</span> and a <span className="text-blue-500 text-xl">Markdown API</span>. It lets you write in a <code>textarea</code> and instantly see a live preview in the container next to it.</>), 
        type:"Front end", 
        githubLink: "https://github.com/Dev-id-A/markdown-previewer", 
        pagesLink:"https://dev-id-a.github.io/markdown-previewer/"
        ,},
    {src: "src/assets/Project/ProjectsImg/drum-machine.png", 
        alt: "Drum machine", 
        descriptionES: (<>En esta aplicación desarrollada con <span className="text-blue-500 text-xl">React</span>, <span className="text-blue-500 text-xl">Bootstrap</span> y <span className="text-blue-500 text-xl">SASS</span>, utilicé <code>useRef</code> para reproducir los beats tanto al hacer clic como al presionar las teclas del teclado.</>), 
        descriptionEN: (<>In this app built with <span className="text-blue-500 text-xl">React</span>, <span className="text-blue-500 text-xl">Bootstrap</span>, and <span className="text-blue-500 text-xl">SASS</span>, I used <code>useRef</code> to play the beats both by clicking and by pressing the keyboard keys.</>), 
        type:"Front end", 
        githubLink: "https://github.com/Dev-id-A/drum-machine", 
        pagesLink:"https://dev-id-a.github.io/drum-machine/"
        ,},
    {src: "src/assets/Project/ProjectsImg/calculator.png", 
        alt: "Calculator", 
        descriptionES: (<>En este proyecto, desarrollado con <span className="text-blue-500 text-xl">React</span>, <span className="text-blue-500 text-xl">Bootstrap</span> y <span className="text-blue-500 text-xl">SASS</span>, utilicé <code>regex</code> para crear una calculadora funcional que con los mínimos errores.</>), 
        descriptionEN: (<>In this project, built with <span className="text-blue-500 text-xl">React</span>, <span className="text-blue-500 text-xl">Bootstrap</span>, and <span className="text-blue-500 text-xl">SASS</span>, I used <code>regex</code> to create a functional calculator with as few errors as possible.</>), 
        type:"Front end", 
        githubLink: "https://github.com/Dev-id-A/calculator", 
        pagesLink:"https://dev-id-a.github.io/calculator/"
        ,},
    {src: "src/assets/Project/ProjectsImg/25-5-clock.png", 
        alt: "25+5 clock", 
        descriptionES: (<>Este proyecto lo hice con <span className="text-blue-500 text-xl">React</span>, <span className="text-blue-500 text-xl">Bootstrap</span> y <span className="text-blue-500 text-xl">SASS</span>. Usé <code>useEffect</code> y un poco de formateo de tiempo para que cada cierto tiempo de un sonido que indica el descanso o cuando debes continuar.</>), 
        descriptionEN: (<>I built this project with <span className="text-blue-500 text-xl">React</span>, <span className="text-blue-500 text-xl">Bootstrap</span>, and <span className="text-blue-500 text-xl">SASS</span>. I used <code>useEffect</code> and some time formatting so that every certain interval a sound goes off to let you know when it’s break time or when you should continue.</>), 
        type:"Front end", 
        githubLink: "https://github.com/Dev-id-A/25-5-clock", 
        pagesLink:"https://dev-id-a.github.io/25-5-clock/"
        ,},
    {src: "src/assets/Project/ProjectsImg/bar-chart.png", 
        alt: "Bar chart", 
        descriptionES: (<></>), 
        descriptionEN: (<></>), 
        type:"Data visualization", 
        githubLink: "https://github.com/Dev-id-A/bar-chart", 
        pagesLink:"https://dev-id-a.github.io/bar-chart/"
        ,},
    {src: "src/assets/Project/ProjectsImg/scatterplot-graph.png", 
        alt: "Scatterplot graph", 
        descriptionES: (<></>), 
        descriptionEN: (<></>), 
        type:"Data visualization", 
        githubLink: "https://github.com/Dev-id-A/scatterplot-graph", 
        pagesLink:"https://dev-id-a.github.io/scatterplot-graph/"
        ,},
    {src: "src/assets/Project/ProjectsImg/heat-map.png", 
        alt: "Heat map", 
        descriptionES: (<></>), 
        descriptionEN: (<></>), 
        type:"Data visualization", 
        githubLink: "https://github.com/Dev-id-A/heat-map", 
        pagesLink:"https://dev-id-a.github.io/heat-map/"
        ,},
    {src: "src/assets/Project/ProjectsImg/choropleth-map.png", 
        alt: "Choropleth map", 
        descriptionES: (<></>), 
        descriptionEN: (<></>), 
        type:"Data visualization", 
        githubLink: "https://github.com/Dev-id-A/choropleth-map", 
        pagesLink:"https://dev-id-a.github.io/choropleth-map/"
        ,},
    {src: "src/assets/Project/ProjectsImg/treemap-diagram.png", 
        alt: "Treemap diagram", 
        descriptionES: (<></>), 
        descriptionEN: (<></>), 
        type:"Data visualization", 
        githubLink: "https://github.com/Dev-id-A/treemap-diagram", 
        pagesLink:"https://dev-id-a.github.io/treemap-diagram/"
        ,}
];